// *** Generated Source File ***
// Portions Copyright (c) 1996-2001, SilverStream Software, Inc., All Rights Reserved

package com.sssw.gen.forms; // generated by SilverStream: do not edit

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Hashtable;
import java.util.Locale;

import javax.swing.JComponent;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

import org.apache.log4j.Logger;

import com.gpc.backofficecommon.FwoSessionMgr;
import com.gpc.backofficecommon.constants.schema.Sch_CoreBankMaintenance;
import com.gpc.backofficecommon.util.SilverStreamExceptionHelper;
import com.gpc.client.backoffice.FwoFormMaster;
import com.gpc.client.backoffice.FwoJTextKeyFilter;
import com.gpc.client.backoffice.FwoToolBarDirector;
import com.gpc.client.backoffice.app.TamsFormMaster;
import com.gpc.client.backoffice.table.TsoJTableMgr;
import com.gpc.client.common.ClientApplicationContext;
import com.gpc.client.common.focusmanager.DefaultFocusDecider;
import com.gpc.client.common.focusmanager.FocusDecider;
import com.gpc.client.common.table.cell.FwoImageIconCell;
import com.gpc.client.common.table.cell.FwoWholeNumberCell;
import com.gpc.client.pointofsale.invoice.line.InvoiceLineBL;
import com.gpc.common.ApplicationContext;
import com.gpc.valueobjects.invoice.line.BaseLineItemVO;
import com.gpc.valueobjects.invoice.line.InvoiceNoteVO;
import com.gpc.valueobjects.customer.CustomerVO;
import javax.swing.Timer;
import java.util.Vector;
import java.util.List;
import java.math.BigDecimal;
import java.util.ArrayList;
import com.gpc.client.common.event.InvoiceEvent;
import com.gpc.client.common.event.PointOfSaleEventDispatcher;
import com.gpc.client.common.event.PointOfSaleListEvent;
import com.gpc.valueobjects.invoice.InvoiceVO;
import com.gpc.common.FwiConstant;
import com.gpc.common.TsoConstant;
import com.gpc.common.exception.ApplicationException;
import com.gpc.common.util.RefStoreConfigurationUtil;
import com.gpc.frame.FwiFormEdit;
import com.gpc.frame.FwiFormProcess;
import com.sssw.rt.form.AgfForm;
import com.sssw.rt.gui.AgoColorManager;
import com.sssw.rt.util.AgoData;
import com.sssw.rt.util.AgoDataConcurrencyException;
import com.sssw.rt.util.AgoInvalidDataException;
import com.sssw.rt.util.AgoMissingDataException;
import com.sssw.rt.util.AgoSecurityException;
import com.sssw.rt.util.AgoTransientSystemException;
import com.sssw.rt.util.AgoUnrecoverableSystemException;
import com.sssw.rt.form.*;

public class FrmIM_CoreBankMaintenance extends AgfForm
        // generated by SilverStream: do not edit
        implements ActionListener, FocusListener, KeyListener, com.gpc.frame.FwiFormProcess,
        FwiFormEdit {
    public javax.swing.JScrollPane tblCoreBankMaintenanceScrollPane;
    public com.sssw.rt.jform.AgcJTable tblCoreBankMaintenance;
    public javax.swing.JScrollPane taReasonTextAreaScrollPane;
    public com.sssw.rt.jform.AgcJLabel lblPartNumDesData;
    public com.sssw.rt.jform.AgcJLabel lblInvNumberData;
    public javax.swing.ButtonGroup DefaultJButtonGroup = new javax.swing.ButtonGroup();
    public com.sssw.rt.jform.AgcJCheckBox ckbStatusCheckbox;
    public com.sssw.rt.jform.AgcJTextArea taReasonTextArea;
    public com.sssw.rt.jform.AgcJLabel lblResonText;
    public com.sssw.rt.jform.AgcJLabel lblStatus;
    public com.sssw.rt.jform.AgcJLabel lblPartNumDes;
    public com.sssw.rt.jform.AgcJLabel lblInvoiceNumber;
    public com.sssw.rt.form.AgcRectangle rectReasonDetails;
    public com.sssw.rt.jform.AgcJButton btnBillBackCore;
    public com.sssw.rt.jform.AgcJLabel lblTitle;
    public com.sssw.rt.form.AgcData agcOpenCores;

    private static final Logger logger = Logger.getLogger(FrmIM_CoreBankMaintenance.class);
    private static final String ERROR_RETRIEVING_OPEN_CORE_LIST = "7121";
    private static final String ERROR_UPDATING_CORE_STATUS = "7122";
    /** The Constant CLOSED_NO_CORE_STATUS_ID. */
    private static final String CLOSED_NO_CORE_STATUS_ID = "6";
    private boolean isEditable = false;

    private TamsFormMaster FM;
    private TsoJTableMgr m_TblMgr;
    private final String[] mPrimaryKeyFields = {
            Sch_CoreBankMaintenance.ID, Sch_CoreBankMaintenance.LOC };
    InvoiceVO invoiceVO = new InvoiceVO();
    InvoiceNoteVO invoiceNoteVO = null;

    public FrmIM_CoreBankMaintenance() {
        // ==== Warning: SilverStream-generated method: do not edit. All changes will be lost ===
    }

    public void init() throws Exception {
        // ==== Warning: SilverStream-generated method: do not edit. All changes will be lost ===
        // Initialize form and data
        this.setTransparent(false);
        this.setBackground(Color.white);
        this.setBackgroundImageMode(1);
        agData.setDataMode(AgoData.DATA_MODE_FIRST_RECORD);
        agDataMgr.setAutomaticValidationUI(true);
        this.setName(TsoConstant.FRM_IM_CORE_BANK_MAINTENANCE);
        this.setBounds(10, 10, 1015, 615);

        // Initialize agcOpenCores
        agcOpenCores = new com.sssw.rt.form.AgcData();
        agcOpenCores.setName("agcOpenCores");
        agcOpenCores.setBounds(55, 85, 910, 265);
        agcOpenCores.setDataSource("com.gpc.tams.dso.dsoCoreBankMaintenance");
        agcOpenCores.setPropertyName(0, Sch_CoreBankMaintenance.ID);
        agcOpenCores.setPropertyName(1, Sch_CoreBankMaintenance.LOC);
        agcOpenCores.setPropertyName(2, TsoConstant.INVOICE_NUMBER);
        agcOpenCores.setPropertyName(3, TsoConstant.INVOICE_DATE);
        agcOpenCores.setPropertyName(4, TsoConstant.LINE);
        agcOpenCores.setPropertyName(5, Sch_CoreBankMaintenance.PART_NUMBER);
        agcOpenCores.setPropertyName(6, Sch_CoreBankMaintenance.REASON);
        agcOpenCores.setPropertyName(7, Sch_CoreBankMaintenance.REF_CORE_STATUS_ID);
        agcOpenCores.setPropertyName(8, Sch_CoreBankMaintenance.MODIFIED_BY_EMPLOYEE_ID);
        agcOpenCores.setPropertyName(9, Sch_CoreBankMaintenance.LAST_MODIFIED_DATE);
        agcOpenCores.setPropertyName(10, Sch_CoreBankMaintenance.LINE_ITEM_CLOSED_DATE);
        agcOpenCores.setPropertyName(11, TsoConstant.STATUS_CLOSEDNOCORE);
        agcOpenCores.setPropertyName(12, TsoConstant.PART_DESCRIPTION);
        agcOpenCores.setPropertyName(13, TsoConstant.KEY_CUSTOMER_NUMBER);
        agcOpenCores.setPropertyName(14, TsoConstant.CUSTOMER_NAME);
        agcOpenCores.setPropertyName(15, TsoConstant.PO_NUMBER);
        agcOpenCores.setPropertyName(16, TsoConstant.QTY_TO_RETURN);
        
        // Initialize tblCoreBankMaintenance
        tblCoreBankMaintenance = new com.sssw.rt.jform.AgcJTable();
        tblCoreBankMaintenance.setName("tblCoreBankMaintenance");
        tblCoreBankMaintenanceScrollPane = new JScrollPane(tblCoreBankMaintenance);
        tblCoreBankMaintenanceScrollPane.setBounds(55,85,910,265);
        tblCoreBankMaintenance.setEditable(false);
        tblCoreBankMaintenance.setCellSelectionEnabled(false);
        tblCoreBankMaintenance.setColumnSelectionAllowed(false);
        tblCoreBankMaintenance.setRowSelectionAllowed(true);
        tblCoreBankMaintenance.setShowGrid(true);
        tblCoreBankMaintenance.setGridColor(Color.gray);
        tblCoreBankMaintenance.setForeground(Color.black);
        tblCoreBankMaintenance.setBackground(Color.white);
        tblCoreBankMaintenance.setSelectionForeground(Color.white);
        tblCoreBankMaintenance.setSelectionBackground(Color.lightGray);
        tblCoreBankMaintenance.setRowHeight(16);
        tblCoreBankMaintenance.setRowMargin(1);
        tblCoreBankMaintenance.getColumnModel().setColumnMargin(1);
        tblCoreBankMaintenance.setFont(new Font("SansSerif", 0, 12));
        // Initialize lblPartNumDesData
        lblPartNumDesData = new com.sssw.rt.jform.AgcJLabel();
        lblPartNumDesData.setName("lblPartNumDesData");
        lblPartNumDesData.setBounds(235, 435, 315, 20);
        lblPartNumDesData.setText(TsoConstant.EMPTY_STRING);
        lblPartNumDesData.setOpaque(false);
        lblPartNumDesData.setTextStyle(0);
        lblPartNumDesData.setForeground(Color.black);
        lblPartNumDesData.setTextShadowColor(Color.darkGray);
        lblPartNumDesData.setTextHighlightColor(Color.gray);
        lblPartNumDesData.setBackground(Color.lightGray);
        lblPartNumDesData.setHorizontalAlignment(SwingConstants.LEFT);
        lblPartNumDesData.setVerticalAlignment(SwingConstants.CENTER);
        lblPartNumDesData.setHorizontalTextPosition(SwingConstants.RIGHT);
        lblPartNumDesData.setVerticalTextPosition(SwingConstants.CENTER);
        lblPartNumDesData.setWordWrap(false);
        lblPartNumDesData.setFont(new Font("SansSerif", 0, 12));
        // Initialize lblInvNumberData
        lblInvNumberData = new com.sssw.rt.jform.AgcJLabel();
        lblInvNumberData.setName("lblInvNumberData");
        lblInvNumberData.setBounds(235, 410, 105, 20);
        lblInvNumberData.setText(TsoConstant.EMPTY_STRING);
        lblInvNumberData.setOpaque(false);
        lblInvNumberData.setTextStyle(0);
        lblInvNumberData.setForeground(Color.black);
        lblInvNumberData.setTextShadowColor(Color.darkGray);
        lblInvNumberData.setTextHighlightColor(Color.gray);
        lblInvNumberData.setBackground(Color.lightGray);
        lblInvNumberData.setHorizontalAlignment(SwingConstants.LEFT);
        lblInvNumberData.setVerticalAlignment(SwingConstants.CENTER);
        lblInvNumberData.setHorizontalTextPosition(SwingConstants.RIGHT);
        lblInvNumberData.setVerticalTextPosition(SwingConstants.CENTER);
        lblInvNumberData.setWordWrap(false);
        lblInvNumberData.setFont(new Font("SansSerif", 0, 12));
        // Initialize ckbStatusCheckbox
        ckbStatusCheckbox = new com.sssw.rt.jform.AgcJCheckBox();
        ckbStatusCheckbox.setName("ckbStatusCheckbox");
        ckbStatusCheckbox.setBounds(235, 465, 15, 15);
        ckbStatusCheckbox.setContentAreaFilled(false);
        ckbStatusCheckbox.setBorderPainted(false);
        ckbStatusCheckbox.setText("Checkbox1");
        ckbStatusCheckbox.setFont(new Font("SansSerif", 0, 12));
        ckbStatusCheckbox.setForeground(Color.black);
        ckbStatusCheckbox.setBackground(AgoColorManager.getColor(224, 223, 227));
        // Initialize taReasonTextArea
        taReasonTextArea = new com.sssw.rt.jform.AgcJTextArea();
        taReasonTextArea.setName("taReasonTextArea");
        taReasonTextAreaScrollPane = new JScrollPane(taReasonTextArea);
        taReasonTextAreaScrollPane.setBounds(235, 490, 705, 75);
        taReasonTextArea.setFont(new Font("SansSerif", 0, 12));
        taReasonTextArea.setLineWrap(true);
        taReasonTextArea.setWrapStyleWord(true);
        taReasonTextArea.setMargin(new Insets(1, 1, 1, 1));
        taReasonTextArea.setEditable(true);
        taReasonTextArea.setForeground(Color.black);
        taReasonTextArea.setBackground(Color.white);
        // Initialize lblResonText
        lblResonText = new com.sssw.rt.jform.AgcJLabel();
        lblResonText.setName("lblResonText");
        lblResonText.setBounds(100, 485, 115, 20);
        lblResonText.setText("Reason Text");
        lblResonText.setOpaque(false);
        lblResonText.setTextStyle(0);
        lblResonText.setForeground(Color.black);
        lblResonText.setTextShadowColor(Color.darkGray);
        lblResonText.setTextHighlightColor(Color.gray);
        lblResonText.setBackground(Color.lightGray);
        lblResonText.setHorizontalAlignment(SwingConstants.RIGHT);
        lblResonText.setVerticalAlignment(SwingConstants.CENTER);
        lblResonText.setHorizontalTextPosition(SwingConstants.RIGHT);
        lblResonText.setVerticalTextPosition(SwingConstants.CENTER);
        lblResonText.setWordWrap(false);
        lblResonText.setFont(new Font("SansSerif", 1, 12));
        // Initialize lblStatus
        lblStatus = new com.sssw.rt.jform.AgcJLabel();
        lblStatus.setName("lblStatus");
        lblStatus.setBounds(75, 460, 140, 20);
        lblStatus.setText("Status - Closed No Core");
        lblStatus.setOpaque(false);
        lblStatus.setTextStyle(0);
        lblStatus.setForeground(Color.black);
        lblStatus.setTextShadowColor(Color.darkGray);
        lblStatus.setTextHighlightColor(Color.gray);
        lblStatus.setBackground(Color.lightGray);
        lblStatus.setHorizontalAlignment(SwingConstants.RIGHT);
        lblStatus.setVerticalAlignment(SwingConstants.CENTER);
        lblStatus.setHorizontalTextPosition(SwingConstants.RIGHT);
        lblStatus.setVerticalTextPosition(SwingConstants.CENTER);
        lblStatus.setWordWrap(false);
        lblStatus.setFont(new Font("SansSerif", 1, 12));
        // Initialize lblPartNumDes
        lblPartNumDes = new com.sssw.rt.jform.AgcJLabel();
        lblPartNumDes.setName("lblPartNumDes");
        lblPartNumDes.setBounds(65, 435, 150, 20);
        lblPartNumDes.setText("Part Number/Description");
        lblPartNumDes.setOpaque(false);
        lblPartNumDes.setTextStyle(0);
        lblPartNumDes.setForeground(Color.black);
        lblPartNumDes.setTextShadowColor(Color.darkGray);
        lblPartNumDes.setTextHighlightColor(Color.gray);
        lblPartNumDes.setBackground(Color.lightGray);
        lblPartNumDes.setHorizontalAlignment(SwingConstants.RIGHT);
        lblPartNumDes.setVerticalAlignment(SwingConstants.CENTER);
        lblPartNumDes.setHorizontalTextPosition(SwingConstants.RIGHT);
        lblPartNumDes.setVerticalTextPosition(SwingConstants.CENTER);
        lblPartNumDes.setWordWrap(false);
        lblPartNumDes.setFont(new Font("SansSerif", 1, 12));
        // Initialize lblInvoiceNumber
        lblInvoiceNumber = new com.sssw.rt.jform.AgcJLabel();
        lblInvoiceNumber.setName("lblInvoiceNumber");
        lblInvoiceNumber.setBounds(115, 410, 100, 20);
        lblInvoiceNumber.setText("Invoice Number");
        lblInvoiceNumber.setOpaque(false);
        lblInvoiceNumber.setTextStyle(0);
        lblInvoiceNumber.setForeground(Color.black);
        lblInvoiceNumber.setTextShadowColor(Color.darkGray);
        lblInvoiceNumber.setTextHighlightColor(Color.gray);
        lblInvoiceNumber.setBackground(Color.lightGray);
        lblInvoiceNumber.setHorizontalAlignment(SwingConstants.RIGHT);
        lblInvoiceNumber.setVerticalAlignment(SwingConstants.CENTER);
        lblInvoiceNumber.setHorizontalTextPosition(SwingConstants.RIGHT);
        lblInvoiceNumber.setVerticalTextPosition(SwingConstants.CENTER);
        lblInvoiceNumber.setWordWrap(false);
        lblInvoiceNumber.setFont(new Font("SansSerif", 1, 12));
      //Initialize billBackCore
        btnBillBackCore = new com.sssw.rt.jform.AgcJButton();
        btnBillBackCore.setName("btnBillBackCore");
        btnBillBackCore.setBounds(820, 349, 125, 25);
        btnBillBackCore.setText("Bill Back Core");
        btnBillBackCore.setEnabled(false);
        btnBillBackCore.setFont(new Font("SansSerif", Font.BOLD, 12));
        btnBillBackCore.setForeground(Color.black);
        btnBillBackCore.setBackground(Color.lightGray);
        btnBillBackCore.setMargin(new Insets(1,1,1,1));       
        btnBillBackCore.setVisible(false);
        // Initialize rectReasonDetails
        rectReasonDetails = new com.sssw.rt.form.AgcRectangle();
        rectReasonDetails.setName("rectReasonDetails");
        rectReasonDetails.setBounds(55, 375, 910, 220);
        rectReasonDetails.setColor(Color.lightGray);
        rectReasonDetails.setBorderStyle(4);
        rectReasonDetails.setText("Reason Detail");
        rectReasonDetails.setFont(new Font("SansSerif", 1, 12));
        rectReasonDetails.setForeground(Color.black);
        rectReasonDetails.setTransparent(true);
        // Initialize lblTitle
        lblTitle = new com.sssw.rt.jform.AgcJLabel();
        lblTitle.setName("lblTitle");
        lblTitle.setBounds(620, 20, 330, 45);
        lblTitle.setText("Core Tracking Maintenance");
        lblTitle.setOpaque(false);
        lblTitle.setTextStyle(0);
        lblTitle.setForeground(AgoColorManager.getColor(24, 24, 231));
        lblTitle.setTextShadowColor(Color.darkGray);
        lblTitle.setTextHighlightColor(Color.gray);
        lblTitle.setBackground(Color.lightGray);
        lblTitle.setHorizontalAlignment(SwingConstants.LEFT);
        lblTitle.setVerticalAlignment(SwingConstants.CENTER);
        lblTitle.setHorizontalTextPosition(SwingConstants.RIGHT);
        lblTitle.setVerticalTextPosition(SwingConstants.CENTER);
        lblTitle.setWordWrap(false);
        lblTitle.setFont(new Font("SansSerif", 3, 25));

        addControls();
        addBindings();

        // Setup tab order
        final Component[] tabOrder = {taReasonTextArea, ckbStatusCheckbox, tblCoreBankMaintenance,btnBillBackCore, };
        setUserDefinedTabOrder(tabOrder);
        return;
    }

    private void handleBillBackCoreActionPerformed() {
    	
    	ClientApplicationContext clientApplicationContext = ClientApplicationContext.getClientApplicationContext();
    	int selectedRow = tblCoreBankMaintenance.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }
        String customerNum = tblCoreBankMaintenance.getValueAt(selectedRow, 0).toString();
        Integer customerNumber = new Integer(customerNum);
        CustomerVO customerVO = null;
        try {
            customerVO = clientApplicationContext.getCustomerDAO().getCustomerDetailInfo(customerNumber);
        } catch (ApplicationException ae) {
            logger.error(ae.toString(), ae);
            clientApplicationContext.getMessageMgr().showMessage(ae.getUserMessageID(),
                    ae.getUserMessageParameters());
            return;
        }
        Integer custId = customerVO.getID();
        Integer loc = new Integer(clientApplicationContext.getLocation());
        String lineAbbr = tblCoreBankMaintenance.getValueAt(selectedRow, 4).toString();
        String partNum = tblCoreBankMaintenance.getValueAt(selectedRow, 5).toString();
        String invoiceNumber = tblCoreBankMaintenance.getValueAt(selectedRow, 2).toString();
        Object poObj = tblCoreBankMaintenance.getValueAt(selectedRow, 10);
        String PO = (poObj != null) ? poObj.toString() : "";
        int quantity = ((Integer) tblCoreBankMaintenance.getValueAt(selectedRow, 7)).intValue();
        generateCoreBillBack(custId,loc,lineAbbr,partNum,invoiceNumber,PO,quantity);
        
	}
    
    private void generateCoreBillBack(Integer custId,Integer loc,String lineAbbr,String partNum,String invoiceNumber,String PO,Integer qty) {
    	Vector vec = new Vector();
    	BaseLineItemVO baseLineItemVO = new BaseLineItemVO();
    	invoiceVO.setLOC(loc);
    	invoiceVO.setCustomerID(custId);
        baseLineItemVO.setLineAbbr(lineAbbr);
        baseLineItemVO.setPartNum(partNum);
    	baseLineItemVO.setDisplayItem(true);
        baseLineItemVO.setQuantityBilled(new BigDecimal(qty));
        baseLineItemVO.setCoreTransaction(true);
        baseLineItemVO.setRequestForCoreBillBack(true);
        invoiceNoteVO = new InvoiceNoteVO();
        invoiceNoteVO.setText("Core bill back from INV # " + invoiceNumber  + " PO # " + PO);
    	
        invoiceNoteVO.setCompletedLine(true);
        invoiceNoteVO.setLineAddedToList(true);
        vec.addElement(baseLineItemVO);
        invoiceVO.setLineItems(vec);
        try {
        	InvoiceLineBL.loadGeneratedLines(invoiceVO); 	
        }
        catch(ApplicationException e) {
        	logger.error("FrmIM_CoreBankMaintenance:generateCoreBillBack()", e);
        }
        
        PointOfSaleEventDispatcher posEventDispather =
                ((ClientApplicationContext) ApplicationContext.getInstance()).getPointOfSaleEventDispatcher();
     
            // Fire invoice loaded
            posEventDispather.fireInvoiceLoaded(new InvoiceEvent(this, invoiceVO, 0, true));
     
            // Dispatch both items in correct order
            SwingUtilities.invokeLater(() -> {
            	javax.swing.Timer timer = new javax.swing.Timer(10, e -> {
                    posEventDispather.fireInvoiceLineItemAdded(
                        new PointOfSaleListEvent(FrmIM_CoreBankMaintenance.this, invoiceNoteVO));
                });
            	timer.setRepeats(false); // Prevent continuous firingtimer.start();
            	timer.start();
            });
    	this.setVisible(false);	
		
    	
    }
    
	private void enableDisableBillBackCoreButton() {

		int selectedRow = tblCoreBankMaintenance.getSelectedRow();
		Boolean isCoreBillBackEnabled = RefStoreConfigurationUtil.isCoreBillBackEnabled();
		btnBillBackCore.setVisible(isCoreBillBackEnabled);
		if (Boolean.TRUE.equals(isCoreBillBackEnabled) && selectedRow != -1) {
			btnBillBackCore.setEnabled(true);
		} else {
			btnBillBackCore.setEnabled(false);
			return;
		}
	}

	protected void addAllFormControls() {
        // ==== Warning: SilverStream-generated method: do not edit. All changes will be lost ===
        this.add(tblCoreBankMaintenanceScrollPane);
        this.add(lblPartNumDesData);
        this.add(lblInvNumberData);
        this.add(ckbStatusCheckbox);
        ckbStatusCheckbox.addActionListener(this);
        this.add(taReasonTextAreaScrollPane);
        taReasonTextArea.addKeyListener(this);
        taReasonTextArea.addFocusListener(this);
        this.add(lblResonText);
        this.add(lblStatus);
        this.add(lblPartNumDes);
        this.add(lblInvoiceNumber);
        this.add(rectReasonDetails);
        this.add(btnBillBackCore);
        btnBillBackCore.addActionListener(this);
        this.add(lblTitle);
        this.add(agcOpenCores);
    }

    protected void formActivate() {

        final Hashtable permissions = new Hashtable();
        permissions.put(FwoToolBarDirector.EDIT_OK, Boolean.TRUE);
        permissions.put(FwoToolBarDirector.SAVE_OK, Boolean.TRUE);
        final FwoToolBarDirector toolBarDirector = new FwoToolBarDirector(permissions);
        FM = new TamsFormMaster(this, (FwiFormProcess) this.getParentForm(), null, toolBarDirector);
        FM.setMode(FwoFormMaster.EDIT_MODE_NOT_EDITING);

        taReasonTextArea.putClientProperty(FocusDecider.NAME, DefaultFocusDecider.getInstance());
        taReasonTextArea.setDocument(new FwoJTextKeyFilter(FwoJTextKeyFilter.ALLKEY, 256, false,
                false));
        taReasonTextArea.setEnabled(false);

        buildTable();
        viewMode();
    }

    private void viewMode() {
        if (FM.getMode() == FM.VIEW_MODE) {
            FM.setSave(false);
            ckbStatusCheckbox.setEnabled(false);
        }
    }

    /**
     * This method is used to Constructs a JTable.
     */
    private void buildTable() {
        // Displayable variable
        final int[] displayableColumns = {13, 14, 2, 3, 4, 5, 12, 16, 11, 6, 15 };

        FwoImageIconCell imageIconCell = new FwoImageIconCell(Boolean.TRUE, Boolean.FALSE);
        imageIconCell.setRendererHorizontalAlignment(SwingConstants.CENTER);
        FwoWholeNumberCell wholeNumCell = new FwoWholeNumberCell(FwiConstant.INTEGER, false);

        try {
            Hashtable params = new Hashtable();
            params.put(Sch_CoreBankMaintenance.LOC, FM.m_loc);
            SilverStreamExceptionHelper.invokeQuery(agcOpenCores, params);
            // display the data in the table
            m_TblMgr = new TsoJTableMgr(this, tblCoreBankMaintenance, agcOpenCores,
                    displayableColumns, null, null, mPrimaryKeyFields);
            m_TblMgr.setColumnWidth(0, 100);
            m_TblMgr.setCustomCell(8, imageIconCell);
            m_TblMgr.setCustomCell(0, wholeNumCell);
            m_TblMgr.setCustomCell(2, wholeNumCell);
			m_TblMgr.setCustomCell(7, wholeNumCell);
            m_TblMgr.setSelectionMode(TsoJTableMgr.SINGLE_SELECTION);
            // sorting of columns not required on table
            m_TblMgr.removeMouseListenerFromTableHeader();
            m_TblMgr.setCanAutoSave(false, false);
            enableDisableBillBackCoreButton();

            // check if open core are available.
            if (agcOpenCores.gotoFirst()) {
                final String invNum = tblCoreBankMaintenance.getValueAt(0, 2).toString();
                final String partNum = tblCoreBankMaintenance.getValueAt(0, 5).toString();
                /*
                 * To fix bug 33274 Check if description exists for the part or not.
                 */
                String partDes = null;
                if (tblCoreBankMaintenance.getValueAt(0, 6) != null) {
                    partDes = tblCoreBankMaintenance.getValueAt(0, 6).toString();
                }

                lblInvNumberData.setText(invNum);
                // if part description is null
                if (partDes == null) {
                    lblPartNumDesData.setText(partNum);
                } else {
                    lblPartNumDesData.setText(partNum + " / " + partDes);
                }
                ckbStatusCheckbox.setSelected(false);
                isEditable = true;
            }
        } catch (ApplicationException e) {
            logger.error("FrmIM_CoreBankMaintenance:buildTable()", e);
            ClientApplicationContext.getClientApplicationContext().getMessageMgr().showMessage(
                    this, ERROR_RETRIEVING_OPEN_CORE_LIST, e.toString());
            return;
        } catch (AgoTransientSystemException e) {
            logger.error("FrmIM_CoreBankMaintenance:buildTable()", e);
            ClientApplicationContext.getClientApplicationContext().getMessageMgr().showMessage(
                    this, "103", e.toString());
            return;
        } catch (AgoUnrecoverableSystemException e) {
            logger.error("FrmIM_CoreBankMaintenance:buildTable()", e);
            ClientApplicationContext.getClientApplicationContext().getMessageMgr().showMessage(
                    this, "103", e.toString());
            return;
        } catch (AgoSecurityException e) {
            logger.error("FrmIM_CoreBankMaintenance:buildTable()", e);
            ClientApplicationContext.getClientApplicationContext().getMessageMgr().showMessage(
                    this, "103", e.toString());
            return;
        }
    }

    public boolean fSave() {
        logger.info("Entering fSave()");
        boolean isCoreStatusUpdated = false;
        if (validateReason()) {
            try {
                agcOpenCores.setProperty(Sch_CoreBankMaintenance.REF_CORE_STATUS_ID,
                        CLOSED_NO_CORE_STATUS_ID);
                FM.setTransactionColumns(agcOpenCores);
                agcOpenCores.setProperty(Sch_CoreBankMaintenance.LINE_ITEM_CLOSED_DATE, FM
                        .getTransactionTimestamp());
                agcOpenCores.updateRows();
                m_TblMgr.refreshRows();
                populateLineItemDetails();
                isCoreStatusUpdated = true;
            } catch (AgoUnrecoverableSystemException e) {
                logger.error("FrmIM_CoreBankMaintenance:fSave()", e);
                ClientApplicationContext.getClientApplicationContext().getMessageMgr().showMessage(
                        this, ERROR_UPDATING_CORE_STATUS, e.toString());
                FwoSessionMgr.getInstance().getNavigationMgr().getMainForm().fRemoveCurrentForm();
            } catch (AgoSecurityException e) {
                logger.error("FrmIM_CoreBankMaintenance:fSave()", e);
                ClientApplicationContext.getClientApplicationContext().getMessageMgr().showMessage(
                        this, ERROR_UPDATING_CORE_STATUS, e.toString());
                FwoSessionMgr.getInstance().getNavigationMgr().getMainForm().fRemoveCurrentForm();
            } catch (AgoInvalidDataException e) {
                logger.error("FrmIM_CoreBankMaintenance:fSave()", e);
                ClientApplicationContext.getClientApplicationContext().getMessageMgr().showMessage(
                        this, ERROR_UPDATING_CORE_STATUS, e.toString());
                FwoSessionMgr.getInstance().getNavigationMgr().getMainForm().fRemoveCurrentForm();
            } catch (AgoMissingDataException e) {
                logger.error("FrmIM_CoreBankMaintenance:fSave()", e);
                ClientApplicationContext.getClientApplicationContext().getMessageMgr().showMessage(
                        this, ERROR_UPDATING_CORE_STATUS, e.toString());
                FwoSessionMgr.getInstance().getNavigationMgr().getMainForm().fRemoveCurrentForm();
            } catch (AgoDataConcurrencyException e) {
                logger.error("FrmIM_CoreBankMaintenance:fSave()", e);
                ClientApplicationContext.getClientApplicationContext().getMessageMgr().showMessage(
                        this, ERROR_UPDATING_CORE_STATUS, e.toString());
                FwoSessionMgr.getInstance().getNavigationMgr().getMainForm().fRemoveCurrentForm();
            } catch (ApplicationException e) {
                logger.error("FrmIM_CoreBankMaintenance:fSave()", e);
                ClientApplicationContext.getClientApplicationContext().getMessageMgr().showMessage(
                        this, ERROR_UPDATING_CORE_STATUS, e.toString());
                FwoSessionMgr.getInstance().getNavigationMgr().getMainForm().fRemoveCurrentForm();
            } catch (AgoTransientSystemException e) {
                logger.error("FrmIM_CoreBankMaintenance:fSave()", e);
                ClientApplicationContext.getClientApplicationContext().getMessageMgr().showMessage(
                        this, ERROR_UPDATING_CORE_STATUS, e.toString());
                FwoSessionMgr.getInstance().getNavigationMgr().getMainForm().fRemoveCurrentForm();
            }
        }
        return isCoreStatusUpdated;
    }

    public boolean fDelete() {
        return false;
    }

    public boolean fEdit() {
        return isEditable;
    }

    public boolean fFindExec() {
        return true;
    }

    public boolean fFindMode() {
        return true;
    }

    public boolean fFirst() {
        return true;
    }

    public boolean fValidateComponent(final javax.swing.JComponent jComponent1) {
        return true;
    }

    public boolean fLast() {
        return false;
    }

    public boolean fNew() {
        return false;
    }

    public boolean fNext() {
        return true;
    }

    public boolean fPrevious() {
        return false;
    }

    public void fSort() {
    }

    public boolean fValidate() {
     return true;
    }

    public boolean fStopLogout() {
        return false;
    }

    public void fCancel() {
        try {
            // Invoke refresh method to reset status check box and text area with default values.
            m_TblMgr.refreshRows();
        } catch (AgoUnrecoverableSystemException e) {
            logger.error("AgoUnrecoverableSystemException in fCancel(): ", e);
        } catch (AgoSecurityException e) {
            logger.error("AgoSecurityException in fCancel(): ", e);
        } catch (AgoTransientSystemException e) {
            logger.error("AgoTransientSystemException in fCancel(): ", e);
        }
    }

    public void fPostEdit() {
        // disable text area.  
        taReasonTextArea.setEnabled(false);
    }

    public void fRetrieve(java.util.Hashtable hashtable1) {
    }

    public void fSetToolBar(java.awt.Component component1) {
    }

    public void fCheckAccess() {
    }

    public void fCheckLogin() {
    }

    public void fStylize() {
    }

    public boolean fValidateJTableCell(com.gpc.client.common.table.FwoJTableMgr fwoJTableMgr1,
            int row, int column) {
        return true;
    }

    public boolean fValidateJTableRow(com.gpc.client.common.table.FwoJTableMgr fwoJTableMgr1,
            int row) {
        if (fwoJTableMgr1 == m_TblMgr) {
            int selectedRow = tblCoreBankMaintenance.getSelectedRow();
            Boolean core_status = new Boolean(
                    tblCoreBankMaintenance.getValueAt(selectedRow, 8).toString());
            String reason_text = (String) tblCoreBankMaintenance.getValueAt(selectedRow, 9);
            if (!core_status.booleanValue() && (reason_text == null 
                    || reason_text.trim().equals(TsoConstant.EMPTY_STRING))) {
                taReasonTextArea.setEnabled(false);
            }
            // If check box is selected and reason is entered in text field 
            if (m_TblMgr.haveRowsChanged() && ckbStatusCheckbox.isSelected()) {
                // Do you want to save your changes?
                Boolean bSave = ClientApplicationContext.getClientApplicationContext()
                        .getMessageMgr().showMessageYesNoCancel(this, "120");
                if (bSave == null) { // clicked Cancel
                    taReasonTextArea.setEnabled(true);
                    return false;
                } else if (bSave.booleanValue()) { // clicked Yes
                    if (!FM.fSave()) {
                        return false;
                    }
                } else { // clicked No
                    FM.fCancel();
                }
            }
            populateLineItemDetails();
        }
        return true;
    }

    public String fCreateTitle() {
        return (String) null;
    }

    public boolean fNeedsUpdate() {
        // Return true when rows are modified and status check box is selected. 
        return (m_TblMgr.haveRowsChanged() && ckbStatusCheckbox.isSelected());
    }

    public void fPostNew() {
    }

    public void fPostSave() {
        // Invoke refresh method to reset status check box and text area with default values.
        refresh();
    }

    public void fPostCancel() {
        // Invoke refresh method to reset status check box and text area with default values.
        refresh();
    }

    public void fPostDelete() {
    }

    public Integer fGetFunctionId() {
        return TsoConstant.IM_CORE_BANK_MAINTENANCE;
    }

    public Locale fGetCurrentRecordLocale(JComponent comp) {
        return (java.util.Locale) null;
    }

    public com.gpc.client.backoffice.FwoFormMaster fGetFormMaster() {
        return FM;
    }

    public void fLocalize() {
        ClientApplicationContext.getClientApplicationContext().getLocalizationMgr().localize(this);
    }

    protected void addBindings() {
        // ==== Warning: SilverStream-generated method: do not edit. All changes will be lost ===
        addExpDependencies();
    }

    public String fGetFormName() {
        return TsoConstant.FRM_IM_CORE_BANK_MAINTENANCE;
    }

    /**
     * This method is used to handle reason text area key released event.
     */
    private void handleReasonTextAreaKeyReleased() {
        // Check if agcOpenCores is not null.
        if (agcOpenCores != null) {
            agcOpenCores.setProperty(Sch_CoreBankMaintenance.REASON, taReasonTextArea.getText());
            tblCoreBankMaintenance.repaint();
        }
    }

    public void keyPressed(KeyEvent keyEvent) {
        // ==== Warning: SilverStream-generated method: do not edit. All changes will be lost ===
        Object src = keyEvent.getSource();
        if (src == taReasonTextArea) {
            handleReasonTextAreaKeyPressed();
            return;
        }
    }

    public void keyTyped(KeyEvent keyEvent) {
        // ==== Warning: SilverStream-generated method: do not edit. All changes will be lost ===
    }

    public void keyReleased(KeyEvent keyEvent) {
        // ==== Warning: SilverStream-generated method: do not edit. All changes will be lost ===
        Object src = keyEvent.getSource();
        if (src == taReasonTextArea) {
            handleReasonTextAreaKeyReleased();
            return;
        }
    }

    /**
     * This method is used to handle reason text area focus lost event.
     */
    private void handleReasonTextAreaFocusLost() {
        String reasonText = taReasonTextArea.getText();
        if (agcOpenCores != null && ckbStatusCheckbox.isSelected()) {
            agcOpenCores.setProperty(TsoConstant.STATUS_CLOSEDNOCORE, Boolean.TRUE);
            agcOpenCores.setProperty(Sch_CoreBankMaintenance.REASON, reasonText.trim());
        }
        tblCoreBankMaintenance.repaint();
    }

    public void focusGained(FocusEvent focusEvent) {
        // ==== Warning: SilverStream-generated method: do not edit. All changes will be lost ===
    }

    public void focusLost(FocusEvent focusEvent) {
        // ==== Warning: SilverStream-generated method: do not edit. All changes will be lost ===
        Object src = focusEvent.getSource();
        if (src == taReasonTextArea) {
            handleReasonTextAreaFocusLost();
            return;
        }
    }

    /**
     * This method is used to handle ckbStatus check box action performed event.
     */
    private void handleStatusCheckboxActionPerformed() {
        if (agcOpenCores != null) {
            if (ckbStatusCheckbox.isSelected()) {
                taReasonTextArea.setEnabled(true);
                FM.setComponentFocus(taReasonTextArea);
                agcOpenCores.setProperty(TsoConstant.STATUS_CLOSEDNOCORE, Boolean.TRUE);
                agcOpenCores.setProperty(
                        Sch_CoreBankMaintenance.REASON, taReasonTextArea.getText());
            } else {
                taReasonTextArea.setText(TsoConstant.EMPTY_STRING);
                agcOpenCores.setProperty(TsoConstant.STATUS_CLOSEDNOCORE, Boolean.FALSE);
                agcOpenCores.setProperty(Sch_CoreBankMaintenance.REASON, TsoConstant.EMPTY_STRING);
                taReasonTextArea.setEnabled(false);
            }
            tblCoreBankMaintenance.repaint();
        }
    }

    public void actionPerformed(ActionEvent evt) {
        // ==== Warning: SilverStream-generated method: do not edit. All changes will be lost ===
        Object src = evt.getSource();
        if (src == ckbStatusCheckbox) {
            handleStatusCheckboxActionPerformed();
            return;
        }
        if(src == btnBillBackCore) {
        	handleBillBackCoreActionPerformed();
        	return;
        }
        super.actionPerformed(evt);
    }

    /**
     * This method is used to handle reason text area key pressed event.
     */
    private void handleReasonTextAreaKeyPressed() {
        if (agcOpenCores != null) {
            agcOpenCores.setProperty(Sch_CoreBankMaintenance.REASON, taReasonTextArea.getText());
            tblCoreBankMaintenance.repaint();
        }
    }

    public void doLayout() {
    }
    
    /**
     * This method is used to reset status check box and text area with default values.
     */
    private void refresh() {
        ckbStatusCheckbox.setSelected(false);
        ckbStatusCheckbox.setEnabled(tblCoreBankMaintenance.getRowCount() > 0);
        taReasonTextArea.setText(TsoConstant.EMPTY_STRING);
        taReasonTextArea.setEnabled(false);
    }
 
    /**
     * This method is used to validate the text area.
     * 
     * @return True if reason is valid otherwise false.
     */
    private boolean validateReason() {
        boolean isValid = true;
        if (ckbStatusCheckbox.isSelected()
                && taReasonTextArea.getText().trim().equals(TsoConstant.EMPTY_STRING)) {
            Runnable validateReason = new Runnable() {
                public void run() {
                    ClientApplicationContext.getClientApplicationContext().getMessageMgr()
                            .showMessage(FM.getCurrentForm(), "7105");
                }
            };
            SwingUtilities.invokeLater(validateReason);
            taReasonTextArea.setEnabled(true);
            taReasonTextArea.setText(TsoConstant.EMPTY_STRING);
            FM.setComponentFocus(taReasonTextArea);
            isValid = false;
        }
        return isValid;
    }
    
    /**
     * This method is used to set selected line item values.
     * 
     * @return True if reason is valid otherwise false.
     */
    private void populateLineItemDetails() {
        lblInvNumberData.setText(null);
        lblPartNumDesData.setText(null);
        ckbStatusCheckbox.setSelected(false);
        int selectedRow = tblCoreBankMaintenance.getSelectedRow();
        enableDisableBillBackCoreButton();
		
        // get customer number, part number, part description and status from table
        String invNum = tblCoreBankMaintenance.getValueAt(selectedRow, 2).toString();
        String partNum = tblCoreBankMaintenance.getValueAt(selectedRow, 5).toString();
        String partDes = null;
        if (tblCoreBankMaintenance.getValueAt(selectedRow, 6) != null) {
            partDes = tblCoreBankMaintenance.getValueAt(selectedRow, 6).toString();
        }
        Boolean status = Boolean.valueOf(tblCoreBankMaintenance.getValueAt(selectedRow, 8)
                .toString());
        ckbStatusCheckbox.setSelected(status.booleanValue());
        lblInvNumberData.setText(invNum);
        if (partDes == null) {
            lblPartNumDesData.setText(partNum);
        } else {
            lblPartNumDesData.setText(partNum + " / " + partDes);
        }
        // set the reason for text area
        String reason = (String) tblCoreBankMaintenance.getValueAt(selectedRow, 9);
        if (reason == null) {
            taReasonTextArea.setText(TsoConstant.EMPTY_STRING);
            taReasonTextArea.setEnabled(false);
        } else {
            taReasonTextArea.setText(reason);
            if (ckbStatusCheckbox.isSelected()) {
                taReasonTextArea.setEnabled(true);
            }
        }
    }
}